Repository KNU-LG/frontend, pull requests merged in 2024-11, with the labels that each got.

#9 webOS 배포 문제 해결 #8
  src/routes/index.tsx
  src/routes/path.ts
Labels: bug

#12 설정 화면 UI 및 기능 구현 #4
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Settings/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/home/components/HomeUI.tsx
  src/pages/home/index.tsx
  src/provider/ColorModeContext.tsx
  src/provider/EditModeContext.tsx
  src/provider/Providers.tsx
  src/routes/index.tsx
  src/styles/reset.css
Labels: feat

#13 hashrouter로 변경하여 path 수정 #11
  src/routes/ProtectedRoute.tsx
  src/routes/path.ts
Labels: feat

#14 위젯 세팅화면 기능 및 구현 #10
  src/api/usePostLogin.tsx
  src/api/usePostRegister.tsx
  src/components/Widgets/DragCon.tsx
  src/pages/Login/LoginForm.tsx
  src/pages/Settings/index.tsx
  src/pages/WidgetsSetting/components/WidgetEditor.tsx
  src/pages/WidgetsSetting/index.tsx
  src/pages/home/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
Labels: feat

#17 Design/#7
  src/components/Button/index.tsx
  src/pages/Login/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
Labels: design

#19 위젯 선택 UI 구현 + 로그인 페이지(백버튼, 텍스트 디자인 일부 변경) #18
  package-lock.json
  package.json
  src/api/instance/index.tsx
  src/api/usePostLogin.tsx
  src/api/usePostRegister.tsx
  src/components/Widgets/DragCon.tsx
  src/components/WidgetsUI/CalendarUI.tsx
  src/pages/Login/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/Settings/index.tsx
  src/pages/Widgets/index.tsx
  src/pages/home/components/HomeUI.tsx
  src/provider/EditModeContext.tsx
  src/provider/PositionContext.tsx
  src/routes/index.tsx
  src/styles/reset.css
  src/types/index.ts
Labels: feat, design

#21 캘린더 widget 구현 + schedule 구현 #15
  src/api/calendar/usePostCalendar.tsx
  src/api/schedule/useDeleteSchedule.tsx
  src/api/schedule/useGetSchedule.tsx
  src/api/schedule/usePostSchedule.tsx
  src/components/Widgets/Calendar.tsx
  src/components/Widgets/Clock.tsx
  src/components/Widgets/Modal/index.tsx
  src/pages/Widgets/index.tsx
  src/pages/WidgetsSetting/components/WidgetEditor.tsx
  src/pages/WidgetsSetting/index.tsx
  src/types/index.ts
Labels: feat

#23 dimming 기능 구현 + calendar 삭제 기능 추가 #22
  src/api/calendar/useDeleteCalendar.tsx
  src/components/Widgets/Calendar.tsx
  src/components/Widgets/DragCon.tsx
  src/pages/Settings/index.tsx
  src/pages/Widgets/components/Calendar.tsx
  src/pages/Widgets/index.tsx
  src/provider/DimmingContext.tsx
  src/provider/PositionContext.tsx
  src/provider/Providers.tsx
  src/styles/reset.css
Labels: feat

#26 홈화면 배경 이미지 업로드 기능 #25
  src/pages/Settings/index.tsx
  src/pages/home/components/HomeUI.tsx
  src/provider/BackgroundContext.tsx
  src/provider/ColorModeContext.tsx
  src/provider/Providers.tsx
Labels: feat

#27 Feat/#20
  package-lock.json
  package.json
  src/api/useGetProfile.tsx
  src/components/Button/index.tsx
  src/pages/MyPage/index.tsx
  src/types/index.ts
Labels: feat

#29 Design/#7
  src/components/Button/index.tsx
  src/pages/Login/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUp/index.tsx
Labels: refactor, design

#31 setting page UI 수정 #28
  src/components/Button/ToggleButton.tsx
  src/index.tsx
  src/pages/Settings/components/BackgroundUI/index.tsx
  src/pages/Settings/components/Button/index.tsx
  src/pages/Settings/index.tsx
  src/styles/reset.css
  src/styles/variables.css
Labels: design

#34 시계위젯 구현 #33
  src/api/calendar/usePostCalendar.tsx
  src/api/clock/usePostClock.tsx
  src/components/Widgets/Clock.tsx
  src/components/WidgetsUI/ClockUI.tsx
  src/pages/Widgets/components/Calendar/index.tsx
  src/pages/Widgets/components/Clock/index.tsx
  src/pages/Widgets/index.tsx
  src/pages/home/components/HomeUI.tsx
  src/types/index.ts
Labels: feat

#35 clock delete 삭제 구현 #33
  src/api/clock/useDeleteClock.tsx
  src/components/Widgets/Clock.tsx
  src/pages/home/components/HomeUI.tsx
Labels: feat
